dist: trusty
sudo: false

language: php

git:
  depth: 5

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.2
  allow_failures:
    - php: 7.2

install:
  - mkdir -p /tmp/test
  - cp -rv ./test/* /tmp/test/
  - cd /tmp/test
  - composer install

script:
  - ./test.sh docteur 1 "Composer version:"
  - ./test.sh spectacle 0 "alexislefebvre/compositeur"
  - ./test.sh met-a-jour 0 "Generating autoload files"
